// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bpFixedPointCPP
Rcpp::List bpFixedPointCPP(const arma::mat& bulk, const arma::mat& ref, int n_iter);
RcppExport SEXP _InstaPrism_bpFixedPointCPP(SEXP bulkSEXP, SEXP refSEXP, SEXP n_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type bulk(bulkSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ref(refSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(bpFixedPointCPP(bulk, ref, n_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_InstaPrism_bpFixedPointCPP", (DL_FUNC) &_InstaPrism_bpFixedPointCPP, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_InstaPrism(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
